' ============================================================
' FactsheetFormatter.bas
' VBA Module: Automated Factsheet Formatting & Refresh
'
' Purpose: Automates the formatting and refresh cycle for
' monthly fund factsheets. Designed to be imported into
' Excel workbooks generated by the Python pipeline.
'
' Modules:
'   1. FormatFactsheet     - Apply client-ready formatting
'   2. RefreshDataLinks    - Simulate data refresh from CSVs
'   3. GenerateCommentary  - Auto-generate performance narrative
'   4. ExportToPDF         - Export formatted sheets to PDF
'   5. RunFullRefresh      - Master routine: refresh + format + export
' ============================================================

Option Explicit

' ────────────────────────────────────────────
' CONSTANTS
' ────────────────────────────────────────────

Private Const HEADER_COLOR As Long = 1712174     ' RGB(46, 26, 26) dark
Private Const ACCENT_COLOR As Long = 5798656     ' RGB(0, 135, 88) green
Private Const NEGATIVE_COLOR As Long = 3158271   ' RGB(255, 47, 48) red
Private Const LIGHT_BG As Long = 15921906        ' RGB(242, 242, 242)
Private Const BORDER_COLOR As Long = 13421772    ' RGB(204, 204, 204)

Private Const FUND_NAME As String = "BlackRock Systematic Global Equity Fund"
Private Const BENCHMARK As String = "MSCI World Index"
Private Const OUTPUT_FOLDER As String = "output\"


' ────────────────────────────────────────────
' MODULE 1: FORMAT FACTSHEET
' ────────────────────────────────────────────

Public Sub FormatFactsheet()
    '
    ' Applies professional formatting to all sheets in the workbook.
    ' Handles: fonts, borders, conditional formatting for positive/negative
    ' values, column widths, and print area setup.
    '
    Dim ws As Worksheet
    Dim lastRow As Long
    Dim lastCol As Long
    Dim rng As Range
    Dim cell As Range
    
    Application.ScreenUpdating = False
    Application.Calculation = xlCalculationManual
    
    For Each ws In ThisWorkbook.Worksheets
        lastRow = ws.Cells(ws.Rows.Count, 2).End(xlUp).Row
        lastCol = ws.Cells(5, ws.Columns.Count).End(xlToLeft).Column
        
        If lastRow < 5 Or lastCol < 2 Then GoTo NextSheet
        
        ' ── Base formatting ──
        ws.Cells.Font.Name = "Calibri"
        ws.Cells.Font.Size = 10
        
        ' ── Format header row (row 5 in data sheets) ──
        If ws.Name <> "Summary" Then
            Set rng = ws.Range(ws.Cells(5, 2), ws.Cells(5, lastCol))
            With rng
                .Font.Bold = True
                .Font.Color = vbWhite
                .Font.Size = 10
                .Interior.Color = HEADER_COLOR
                .HorizontalAlignment = xlCenter
                .Borders.LineStyle = xlContinuous
                .Borders.Color = BORDER_COLOR
            End With
        End If
        
        ' ── Format data cells with conditional coloring ──
        If lastRow > 5 And lastCol > 2 Then
            Set rng = ws.Range(ws.Cells(6, 3), ws.Cells(lastRow, lastCol))
            
            For Each cell In rng
                If IsNumeric(cell.Value) And cell.Value <> 0 Then
                    ' Apply color for percentage columns
                    If InStr(1, ws.Cells(5, cell.Column).Value, "Effect", vbTextCompare) > 0 Or _
                       InStr(1, ws.Cells(5, cell.Column).Value, "Active", vbTextCompare) > 0 Or _
                       InStr(1, ws.Cells(5, cell.Column).Value, "Return", vbTextCompare) > 0 Then
                        
                        If cell.Value > 0 Then
                            cell.Font.Color = ACCENT_COLOR
                            cell.Font.Bold = True
                        ElseIf cell.Value < 0 Then
                            cell.Font.Color = NEGATIVE_COLOR
                            cell.Font.Bold = True
                        End If
                    End If
                End If
                
                ' Apply borders
                cell.Borders.LineStyle = xlContinuous
                cell.Borders.Color = BORDER_COLOR
                cell.Borders.Weight = xlThin
            Next cell
        End If
        
        ' ── Auto-fit columns ──
        ws.Columns("B:" & Chr(64 + lastCol)).AutoFit
        
        ' ── Set print area ──
        ws.PageSetup.PrintArea = ws.Range(ws.Cells(1, 1), ws.Cells(lastRow + 2, lastCol)).Address
        ws.PageSetup.Orientation = xlLandscape
        ws.PageSetup.FitToPagesWide = 1
        ws.PageSetup.FitToPagesTall = False
        
NextSheet:
    Next ws
    
    Application.Calculation = xlCalculationAutomatic
    Application.ScreenUpdating = True
    
    MsgBox "Factsheet formatting complete.", vbInformation, "Format Complete"
End Sub


' ────────────────────────────────────────────
' MODULE 2: REFRESH DATA FROM CSV
' ────────────────────────────────────────────

Public Sub RefreshDataLinks()
    '
    ' Imports updated CSV data from the output folder.
    ' Clears existing data ranges and repopulates from
    ' the latest pipeline output files.
    '
    Dim basePath As String
    Dim ws As Worksheet
    Dim csvPath As String
    Dim fileMap As Object
    
    basePath = ThisWorkbook.Path & "\" & OUTPUT_FOLDER
    
    ' Map sheet names to CSV files
    Set fileMap = CreateObject("Scripting.Dictionary")
    fileMap.Add "Monthly Detail", "sector_attribution.csv"
    fileMap.Add "AUM & Flows", "..\data\aum_flows.csv"
    
    Dim key As Variant
    For Each key In fileMap.Keys
        csvPath = basePath & fileMap(key)
        
        If Dir(csvPath) <> "" Then
            Set ws = Nothing
            On Error Resume Next
            Set ws = ThisWorkbook.Worksheets(CStr(key))
            On Error GoTo 0
            
            If Not ws Is Nothing Then
                ImportCSVToSheet ws, csvPath, 6  ' Data starts at row 6
            End If
        Else
            Debug.Print "File not found: " & csvPath
        End If
    Next key
    
    MsgBox "Data refresh complete.", vbInformation, "Refresh Complete"
End Sub


Private Sub ImportCSVToSheet(ws As Worksheet, csvPath As String, startRow As Long)
    '
    ' Helper: imports a CSV file into a worksheet starting at specified row.
    ' Preserves headers and formatting.
    '
    Dim lastDataRow As Long
    Dim qt As QueryTable
    
    ' Clear existing data (preserve headers)
    lastDataRow = ws.Cells(ws.Rows.Count, 2).End(xlUp).Row
    If lastDataRow >= startRow Then
        ws.Range(ws.Cells(startRow, 1), ws.Cells(lastDataRow, 20)).ClearContents
    End If
    
    ' Import CSV
    Set qt = ws.QueryTables.Add( _
        Connection:="TEXT;" & csvPath, _
        Destination:=ws.Cells(startRow, 2))
    
    With qt
        .TextFileConsecutiveDelimiter = False
        .TextFileCommaDelimiter = True
        .TextFileParseType = xlDelimited
        .RefreshStyle = xlOverwriteCells
        .Refresh BackgroundQuery:=False
        .Delete  ' Remove query table but keep data
    End With
End Sub


' ────────────────────────────────────────────
' MODULE 3: GENERATE PERFORMANCE COMMENTARY
' ────────────────────────────────────────────

Public Sub GenerateCommentary()
    '
    ' Auto-generates a text-based performance commentary
    ' based on the data in the Summary sheet. Writes to a
    ' new "Commentary" sheet.
    '
    Dim wsSummary As Worksheet
    Dim wsComm As Worksheet
    Dim lastRow As Long
    Dim fundReturn As Double
    Dim benchReturn As Double
    Dim activeReturn As Double
    Dim bestMonth As String
    Dim worstMonth As String
    Dim bestVal As Double
    Dim worstVal As Double
    Dim i As Long
    Dim commentary As String
    
    Set wsSummary = ThisWorkbook.Worksheets("Summary")
    
    ' Delete existing commentary sheet
    On Error Resume Next
    Application.DisplayAlerts = False
    ThisWorkbook.Worksheets("Commentary").Delete
    Application.DisplayAlerts = True
    On Error GoTo 0
    
    Set wsComm = ThisWorkbook.Worksheets.Add(After:=ThisWorkbook.Worksheets(ThisWorkbook.Worksheets.Count))
    wsComm.Name = "Commentary"
    wsComm.Tab.Color = RGB(255, 143, 0)
    
    ' ── Extract key data points ──
    ' Find the monthly returns table (starts after "MONTHLY RETURNS" label)
    Dim dataStartRow As Long
    dataStartRow = 0
    For i = 1 To 50
        If CStr(wsSummary.Cells(i, 2).Value) = "Month" Then
            dataStartRow = i + 1  ' Data starts right after header row
            Exit For
        End If
    Next i
    
    If dataStartRow = 0 Then
        MsgBox "Could not find monthly returns data.", vbExclamation
        Exit Sub
    End If
    
    ' Calculate totals and find best/worst months
    bestVal = -999
    worstVal = 999
    Dim monthCount As Long
    monthCount = 0
    
    i = dataStartRow
    Do While wsSummary.Cells(i, 2).Value <> ""
        Dim monthFund As Double
        Dim monthActive As Double
        
        monthFund = wsSummary.Cells(i, 3).Value
        monthActive = wsSummary.Cells(i, 5).Value
        
        If monthFund > bestVal Then
            bestVal = monthFund
            bestMonth = CStr(wsSummary.Cells(i, 2).Value)
        End If
        If monthFund < worstVal Then
            worstVal = monthFund
            worstMonth = CStr(wsSummary.Cells(i, 2).Value)
        End If
        
        monthCount = monthCount + 1
        i = i + 1
    Loop
    
    ' Read cumulative metrics from key metrics section
    fundReturn = wsSummary.Cells(7, 3).Value
    benchReturn = wsSummary.Cells(8, 3).Value
    activeReturn = wsSummary.Cells(9, 3).Value
    
    ' ── Build commentary ──
    commentary = FUND_NAME & " - Performance Commentary" & vbCrLf & vbCrLf
    
    commentary = commentary & "PERIOD OVERVIEW" & vbCrLf
    commentary = commentary & String(40, "-") & vbCrLf
    
    If activeReturn > 0 Then
        commentary = commentary & "The fund delivered a cumulative return of " & _
            Format(fundReturn, "0.00%") & " over the reporting period, " & _
            "outperforming the " & BENCHMARK & " by " & _
            Format(activeReturn, "0.00%") & ". "
    Else
        commentary = commentary & "The fund returned " & _
            Format(fundReturn, "0.00%") & " over the reporting period, " & _
            "underperforming the " & BENCHMARK & " by " & _
            Format(Abs(activeReturn), "0.00%") & ". "
    End If
    
    commentary = commentary & vbCrLf & vbCrLf
    commentary = commentary & "The strongest month was " & bestMonth & _
        " (" & Format(bestVal, "+0.00%;-0.00%") & "), " & _
        "while the weakest was " & worstMonth & _
        " (" & Format(worstVal, "+0.00%;-0.00%") & ")." & vbCrLf & vbCrLf
    
    commentary = commentary & "ATTRIBUTION HIGHLIGHTS" & vbCrLf
    commentary = commentary & String(40, "-") & vbCrLf
    commentary = commentary & "Refer to the Sector Attribution tab for a full Brinson-Hood-Beebower " & _
        "decomposition of active return into allocation, selection, and interaction effects." & vbCrLf & vbCrLf
    
    commentary = commentary & "Note: This commentary is auto-generated from portfolio data. " & _
        "It should be reviewed and supplemented with qualitative market context " & _
        "before distribution to clients."
    
    ' ── Write to sheet ──
    wsComm.Columns("A").ColumnWidth = 2
    wsComm.Columns("B").ColumnWidth = 90
    
    wsComm.Cells(2, 2).Value = FUND_NAME
    wsComm.Cells(2, 2).Font.Name = "Calibri"
    wsComm.Cells(2, 2).Font.Bold = True
    wsComm.Cells(2, 2).Font.Size = 14
    
    wsComm.Cells(3, 2).Value = "Auto-Generated Performance Commentary"
    wsComm.Cells(3, 2).Font.Name = "Calibri"
    wsComm.Cells(3, 2).Font.Color = RGB(102, 102, 102)
    
    ' Write commentary line by line
    Dim lines() As String
    lines = Split(commentary, vbCrLf)
    For i = 0 To UBound(lines)
        wsComm.Cells(5 + i, 2).Value = lines(i)
        wsComm.Cells(5 + i, 2).Font.Name = "Calibri"
        wsComm.Cells(5 + i, 2).Font.Size = 10
        wsComm.Cells(5 + i, 2).WrapText = True
        
        ' Bold section headers
        If Right(lines(i), 1) <> " " And InStr(lines(i), "-") = 0 And _
           Len(lines(i)) > 3 And UCase(lines(i)) = lines(i) Then
            wsComm.Cells(5 + i, 2).Font.Bold = True
            wsComm.Cells(5 + i, 2).Font.Size = 11
        End If
    Next i
    
    MsgBox "Commentary generated on 'Commentary' sheet.", vbInformation, "Commentary Complete"
End Sub


' ────────────────────────────────────────────
' MODULE 4: EXPORT TO PDF
' ────────────────────────────────────────────

Public Sub ExportToPDF()
    '
    ' Exports all formatted sheets to a single PDF file.
    ' Named with fund name and current date for version control.
    '
    Dim pdfPath As String
    Dim dateStr As String
    
    dateStr = Format(Date, "YYYY-MM-DD")
    pdfPath = ThisWorkbook.Path & "\output\Factsheet_" & dateStr & ".pdf"
    
    ' Select all sheets for export
    Dim sheetNames() As String
    Dim ws As Worksheet
    Dim idx As Long
    
    ReDim sheetNames(1 To ThisWorkbook.Worksheets.Count)
    For Each ws In ThisWorkbook.Worksheets
        idx = idx + 1
        sheetNames(idx) = ws.Name
    Next ws
    
    ThisWorkbook.Worksheets(sheetNames).Select
    
    ActiveSheet.ExportAsFixedFormat _
        Type:=xlTypePDF, _
        Filename:=pdfPath, _
        Quality:=xlQualityStandard, _
        IncludeDocProperties:=True, _
        IgnorePrintAreas:=False, _
        OpenAfterPublish:=False
    
    ThisWorkbook.Worksheets(1).Select
    
    MsgBox "PDF exported to:" & vbCrLf & pdfPath, vbInformation, "Export Complete"
End Sub


' ────────────────────────────────────────────
' MODULE 5: MASTER REFRESH ROUTINE
' ────────────────────────────────────────────

Public Sub RunFullRefresh()
    '
    ' Master routine that executes the complete monthly
    ' factsheet production cycle:
    '   1. Refresh data from latest CSV outputs
    '   2. Apply formatting
    '   3. Generate commentary
    '   4. Export to PDF
    '
    Dim startTime As Double
    startTime = Timer
    
    ' Step 1: Refresh
    Application.StatusBar = "Step 1/4: Refreshing data..."
    Call RefreshDataLinks
    
    ' Step 2: Format
    Application.StatusBar = "Step 2/4: Applying formatting..."
    Call FormatFactsheet
    
    ' Step 3: Commentary
    Application.StatusBar = "Step 3/4: Generating commentary..."
    Call GenerateCommentary
    
    ' Step 4: Export
    Application.StatusBar = "Step 4/4: Exporting to PDF..."
    Call ExportToPDF
    
    Application.StatusBar = False
    
    Dim elapsed As Double
    elapsed = Round(Timer - startTime, 1)
    
    MsgBox "Full factsheet refresh complete." & vbCrLf & _
           "Time elapsed: " & elapsed & " seconds.", _
           vbInformation, "Refresh Complete"
End Sub
